### ISSUE TITLE
Error while using the Quarkus web template

### ISSUE THREAD

**Issue by christophe-f** [janus-idp/software-templates#30]
In the step 'step tenant Argcd Fetch Skeleton + Template'

```
Writing file components/${{values.component_id}}-argocd-app-dev.yaml to template output path with mode 33188. {"timestamp":"2022-11-14T22:46:12.546Z"}
Error: (unknown path) [Line 5, Column 40]
    Error: Unable to call `values["application"]["split"]`, which is undefined or falsey
      at render (vm.js:10440:93)
```

**Comment by mattheh** [comment]
This should be resolved by adding the input parameter that the step is referencing, addressed in the linked PR.

However, the templating will still fail on the following step due to the `pull-request` actions looking for a `-gitops` repo in the targeted org, which is currently not being created.  I can take a look at that next, perhaps another issue can be opened to track that

**Comment by mattheh** [comment]
We've decided to go another direction with the fix, instead changing the references to the `application` input back to `organization`.  Linking the new PR
